---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create authentik user
  user:
    name: authentik
    state: present

- name: Add authentik user to docker group
  user:
    name: authentik
    groups: docker
    append: yes

- name: Ensure /opt/authentik directory exists
  file:
    path: /opt/authentik
    state: directory
    owner: authentik
    group: authentik
    mode: '0755'