---
- name: Copy authentik.service to remote host
  copy:
    src: ./files/authentik.service
    dest: /etc/systemd/system/authentik.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: yes

- name: Enable and start authentik service
  systemd:
    name: authentik
    enabled: yes
    state: started